language: android
sudo: false
env:
  global:
  - GRADLE_OPTS="-Xmx1024m -XX:MaxPermSize=1024m"
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
notifications:
  slack: 28go:m5tgpxI8qxVLSbTR1Z2bDeT1
